import { createElement } from 'lwc';
import Comrvivideo65ConditionalRendering from 'c/comrvivideo65ConditionalRendering';

describe('c-comrvivideo65-conditional-rendering', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-comrvivideo65-conditional-rendering', {
            is: Comrvivideo65ConditionalRendering
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});